### ISSUE TITLE
undo key triggers "E684: list index out of range: 5"

### ISSUE THREAD

**Issue by sunaku** [pseewald/AnyFold#6] opened 2016-11-21 17:34 UTC
```vim
Error detected while processing function <SNR>335_ReloadFolds:                                                                 
line   10:                                                                                                                     
E684: list index out of range: 5                                                                                               
Press ENTER or type command to continue                                                                                        
Error detected while processing function <SNR>335_ReloadFolds:                                                                 
line   10:                                                                                                                     
E15: Invalid expression: s:LineIndent(curr_line) != b:anyfold_ind_actual[curr_line - 1]  
```

**Comment by pseewald** [comment] 2016-11-22 11:33
I can not reproduce this, can you be more specific in what situation this happens (what is the action you undo?). I can not see how the index can be out of range, since this line where the error happens is only executed if the total number of lines has not changed (`anyfold_ind_actual` is a list of size number of lines).

**Comment by sunaku** [comment] 2016-11-22 20:07
Sorry about the lack of instructions to reproduce the issue. :cold_sweat:  Try this:
1. Start Vim.
2. Run `:setfiletype mail`
3. Insert the word "hello" by typing `ihello<ESC>`
4. Open a new line and insert "world" by typing `oworld<ESC>`
5. Trigger the undo mechanism by typing `u`
6. Observe the error message.

**Comment by pseewald** [comment] 2016-11-22 21:08
Thanks! But I don't get an error message. In fact, when I undo, the line that triggers the error message is not even executed (it should not be executed if the number of lines has changed).

Could you try the following to narrow down the bug:

in autoload/anyfold.vim of the vim-anyfold directory, put a statement that prints `delta_lines`, this is the number of lines that have been added / removed:

```
diff --git a/autoload/anyfold.vim b/autoload/anyfold.vim
index e293498..a5bac91 100644
--- a/autoload/anyfold.vim
+++ b/autoload/anyfold.vim
@@ -369,6 +369,7 @@ function! s:ReloadFolds(lnum) abort

     let delta_lines = line('$') - len(b:anyfold_ind_actual)

+    echom delta_lines
     if delta_lines == 0
         let indents_same = 1
         let curr_line = changed[0]
```

Then run the example you specified above. Afterwards get the printed numbers by running `:messages`. What numbers do you see (ignoring all messages that are not a number)? I get 0, 1, -1, as expected.

**Comment by pseewald** [comment] 2016-11-25 13:44
I could reproduce the issue with a similar example:

1. Start Vim
2. type `ihello<ESC>`
3. yank and paste hello to end of line by typing `yiw$p`
4. Trigger the undo mechanism by typing `u`

This must be a bug of vim: when you now try to jump to last changed character using `']`, you get the error message
`E19: Mark has invalid line number`

vim-anyfold is relying on `'[` & `']` to get the first and last line of the changed text.

I'll implement a workaround that checks that `']` does not exceed the last line.

**Comment by pseewald** [comment] 2016-11-29 10:10
I committed a workaround that solves this problem for vim-anyfold and I filed an issue vim/vim#1281.

**Closed as completed** 2016-11-29 10:11 UTC

**Comment by sunaku** [comment] 2016-11-29 18:04
Confirmed! That workaround fixed the error for me, thanks! :+1:
